[package]
distribution = "2201.13.0"
org = "ballerinax"
name = "sap.commerce.webservices"
version = "0.9.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["category/connector", "vendor/sap", "domain/commerce", "area/integration", "protocol/rest"]
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerinax-sap.commerce.webservices"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
