[package]
org = "wso2"
name = "procurement_cost_center_setup"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "sap.commerce.webservices"
version = "0.1.0"
repository = "local"
